on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        config:
          - otp: 24
            elixir: 1.15
          - otp: 25
            elixir: 1.15
          - otp: 25
            elixir: 1.18
          - otp: 28
            elixir: 1.19
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.config.otp}}
          elixir-version: ${{matrix.config.elixir}}
      - run: mix deps.get
      - run: mix test
